### ISSUE TITLE
Bad target port providing

### ISSUE THREAD

**Issue by warren-ru** [rluisr/trex_exporter#5]
When I try to provide API port like:
``` yaml
   static_configs:
      - targets:
          - "http://10.10.40.1:4059?worker=t-rex"
``` 
I'm getting exporter error:
`Get "http://10.10.40.1:4059:4059/summary": dial tcp: lookup 10.10.40.1:4059: no such host`

Looks like port duplicating.
